language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - composer require codeclimate/php-test-reporter:dev-master --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=1786358179f1e810a68cd507c40f7f8fac0f8ec76b675396ddddd412d0293379 ./vendor/bin/test-reporter