language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
